### ISSUE TITLE
Peer-to-Peer Review for the newsweek-clone from team#111, the sunbeans

### ISSUE THREAD

**Issue by temesghentekeste** [tGodson/Newsweek-Clone#1]
Positive Aspect of the project:
  - The overall project is starting to have the desired layout and it is in good shape
  -  The semantics of the page is well structured

Things need to be improved:
  - The content is aligned in the center 
  - The heroes section caption sare floating and expanded to occupy their entire container
   - To avoid overflow you can use max-width or bootstrap class container-fluid
   - The google font is required to be loaded either in your HTML or CSS file
    - Some images are floating out
    - The navbar needs some modification
    - Order of heroes section should be below everything in mobile display, instead of an order class 
      using a  different HTML for a different screen size would work out
     - It would be helpful for the programmer to use cards, and other bootstrap classes like justify-content-between, d-flex and other classes right out of the box from bootstrap and it would enable him to avoid to reacreating them in his custom css file

**Comment by tGodson** [comment]
all done. thanks
