### ISSUE TITLE
Peer-to-Peer Review for the newsweek-clone from team#111, the sunbeans

### ISSUE THREAD

**Issue by temesghentekeste** [tGodson/Newsweek-Clone#3]
Positive Aspects of the project:
 - The project is completed and looks awesome in all screen sizes
 - The usage of Bootstrap like classes in the CSS file was professional and made the CSS to follow DRY principles
 - The usage of attribute selectors in the CSS was perfect

Things needed to be improved:
 - The text on the more stories section should be wrapped below the images: using a float with clearfix would solve the problem
 - The d-lg-inline should be removed in the span

Optional improvements
 - Making the middle section sticky when the page scrolls using CSS or JavaScript would  make the website look more professional

**Comment by tGodson** [comment]
thanks.
